# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.9'
auto_detect_solc = false
optimizer_runs = 5_000
broadcast="logs"


[rpc_endpoints]
goerli = "https://goerli.infura.io/v3/8248d583c43446a9be9c0f56790bed32"
sepolia = "https://sepolia.infura.io/v3/1b1d8eead5a24420aa64cff5249c8631"

[etherscan]
goerli = { key = "GB21S43AIXEV5NNDBN6MTEK8X6K8FF97U" }

